import esbuild from "esbuild";
import process from "process";
import { readFileSync } from "fs";

const banner = `/*\nTHIS IS A GENERATED/BUNDLED FILE BY ESBUILD\nIf you want to view the source, please visit the plugin repository.\n*/`;

const manifest = JSON.parse(readFileSync("manifest.json", "utf8"));
const version = manifest.version;

const args = process.argv.slice(2);
const watch = args.includes("--watch");

const baseConfig = {
  entryPoints: ["src/main.ts"],
  bundle: true,
  outfile: "main.js",
  platform: "node",
  target: "es2020",
  format: "cjs",
  sourcemap: false,
  banner: { js: banner },
  external: ["obsidian"],
  define: {
    __VERSION__: JSON.stringify(version)
  }
};

if (watch) {
  const ctx = await esbuild.context(baseConfig);
  await ctx.watch();
  console.log("Watching for changes...");
} else {
  await esbuild.build(baseConfig);
  console.log("Build complete");
}
